apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: signal-minio
  name: signal-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signal-minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: signal-minio
    spec:
      containers:
        - args:
            - server
            - --address
            - {{ .Values.minio.host }}:{{ .Values.minio.port }}
            - /export
          env:
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.accessKey }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.minio.secretKey }}
          image: {{ .Values.minio.image }}:{{ .Values.minio.tag }}
          imagePullPolicy: Always
          name: signal-minio
          ports:
            - containerPort: {{ .Values.minio.port }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /export
              name: signal-minio-data-pvc
            - mountPath: /root/.minio
              name: signal-minio-config-pvc
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: signal-minio-data-pvc
          persistentVolumeClaim:
            claimName: signal-minio-data-pvc
        - name: signal-minio-config-pvc
          persistentVolumeClaim:
            claimName: signal-minio-config-pvc
status: {}
