apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: signal-redis
  name: signal-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signal-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: signal-redis
    spec:
      containers:
        - image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
          imagePullPolicy: Always
          name: signal-redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
