apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: signal-turn
  name: signal-turn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signal-turn
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: signal-turn
    spec:
      containers:
        - env:
            - name: EXTERNAL_IP
              value: {{ .Values.externalIp }}
            - name: TURN_HIGH
              value: "{{ .Values.turn.highPort }}"
            - name: TURN_LOW
              value: "{{ .Values.turn.lowPort }}"
            - name: TURN_REALM
              value: {{ .Values.turn.realm }}
            - name: TURN_SECRET
              value: {{ .Values.turn.secret }}
          image: {{ .Values.registry }}signal-turn:latest
          imagePullPolicy: Always
          name: signal-turn
          ports:
{{- range untilStep (int .Values.turn.lowPort) (int (add1 .Values.turn.highPort)) 1 }}
            - protocol: UDP
              containerPort: {{ toYaml . | trim }}
{{- end }}
            - containerPort: 3478
              protocol: UDP
            - containerPort: 3478
              protocol: TCP
            - containerPort: 3479
              protocol: UDP
            - containerPort: 3479
              protocol: TCP
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: ""
      volumes: null
status: {}
