apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signal-minio-profiles
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/worker-shutdown-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.org/mergeable-ingress-type: minion
    nginx.ingress.kubernetes.io/rewrite-target: /{{ .Values.minio.bucketProfiles }}/$2
spec:
  rules:
    - host: {{ .Values.minio.endpointProfiles }}
      http:
        paths:
          - backend:
              serviceName: signal-minio
              servicePort: {{ .Values.minio.port }}
            path: /()(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signal-minio-attachments
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/worker-shutdown-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.org/mergeable-ingress-type: minion
spec:
  rules:
    - host: {{ .Values.minio.endpointAttachments }}
      http:
        paths:
          - backend:
              serviceName: signal-minio
              servicePort: {{ .Values.minio.port }}
