apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: signal-postgresql
  name: signal-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signal-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: signal-postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.dbPassword }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.dbUser }}
          image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag }}
          imagePullPolicy: Always
          name: signal-postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: signal-postgresql-pvc
            - mountPath: /docker-entrypoint-initdb.d/
              name: signal-postgresql-configmap
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: signal-postgresql-pvc
          persistentVolumeClaim:
            claimName: signal-postgresql-pvc
        - name: signal-postgresql-configmap
          configMap:
            name: signal-postgresql-configmap
            defaultMode: 0755
status: {}
