apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: signal-server
  name: signal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signal-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: signal-server
    spec:
      containers:
        - image: {{ .Values.registry }}signal-server:latest
          imagePullPolicy: Always
          name: signal-server
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /Signal-Server/config/
              name: signal-server-configmap
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: ""
      volumes:
        - name: signal-server-configmap
          configMap:
            name: signal-server-configmap
status: {}
